---
- name: Установка пакетов OpenLDAP
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - slapd
    - ldap-utils
    - debconf-utils

- name: Предварительная настройка slapd
  debconf:
    name: slapd
    question: "{{ item.question }}"
    value: "{{ item.value }}"
    vtype: "{{ item.vtype }}"
  loop: "{{ slapd_debconf }}"

- name: Удаляем debconf-utils
  apt:
    name: debconf-utils
    state: absent

- name: Применяем настройки slapd
  command: dpkg-reconfigure -f noninteractive slapd
