- name: Установка и настройка OpenLDAP
  hosts: ldap-server
  become: yes
  vars_files:
    - vars.yml
    - vault.yml  
  roles:
    - openldap
    - openldap-modules
    - openldap-config
    - openldap-verify
