slapd_debconf:
  - { question: "slapd/internal/generated_adminpw", value: "{{ ldap_admin_pass }}", vtype: "password" }
  - { question: "slapd/internal/adminpw", value: "{{ ldap_admin_pass }}", vtype: "password" }
  - { question: "slapd/password1", value: "{{ ldap_admin_pass }}", vtype: "password" }
  - { question: "slapd/password2", value: "{{ ldap_admin_pass }}", vtype: "password" }
  - { question: "slapd/domain", value: "{{ ldap_domain }}", vtype: "string" }
  - { question: "slapd/organization", value: "{{ ldap_org }}", vtype: "string" }
  - { question: "slapd/no_configuration", value: "false", vtype: "boolean" }
  - { question: "slapd/purge_database", value: "false", vtype: "boolean" }
  - { question: "slapd/move_old_database", value: "true", vtype: "boolean" }
